services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - todo-net

  frontend:
    build: ./frontend
    ports:
      - "5173:80"      # browser → nginx → built React app
    depends_on:
      - backend
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
